[project]
name = "zenoh-python"
version = "0.1.0"
dependencies = [
    "eclipse-zenoh @ git+https://github.com/eclipse-zenoh/zenoh-python@main",
]
requires-python = "==3.8.*"

[tool.pdm]
distribution = false
