build: build_c build_cpp

clean: clean_c clean_cpp

build_c:
    cmake ./zenoh-c -B ./zenoh-c/build
    cmake --build ./zenoh-c/build

test_c:
    ./test-c.sh

clean_c:
    rm -rf ./zenoh-c/build

build_cpp:
    cmake ./zenoh-cpp -B ./zenoh-cpp/build
    cmake --build ./zenoh-cpp/build

test_cpp:
    ./test-cpp.sh

clean_cpp:
    rm -rf ./zenoh-cpp/build

build_python:
    cd zenoh-python && pdm install

test_python:
    ./test-python.sh
